"""Expose one skill source and generate Copilot adapters from Claude profiles.

Run after cloning or editing canonical agents/skills. --check writes nothing.
Native skill aliases are symlinks (Windows junction fallback without elevation),
never copied skill definitions. Never overwrite a nonempty real alias directory.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
from pathlib import Path

from content_common import REPO_ROOT, metadata, sha256_file

SKILLS = Path(".agents/skills")
AGENTS = Path(".claude/agents")
COPILOT = Path(".github/agents")
TOOL_ALIASES = {
    "Read": "read", "Glob": "search", "Grep": "search", "Edit": "edit", "Write": "edit",
    "WebFetch": "web", "WebSearch": "web", "Bash": "execute", "PowerShell": "execute",
    "TodoWrite": "todo", "Agent": "agent",
}


def render_copilot_agent(path: Path) -> str:
    text = path.read_text(encoding="utf-8-sig")
    fields = metadata(text)
    tools = fields.get("tools", "")
    if not tools.startswith("[") or not tools.endswith("]"):
        raise ValueError(f"Expected explicit native tool list: {path}")
    native = [tool.strip().strip("\"'") for tool in tools[1:-1].split(",")]
    unknown = sorted(set(native) - TOOL_ALIASES.keys())
    if unknown:
        raise ValueError(f"Unmapped tools in {path}: {unknown}")
    aliases = list(dict.fromkeys(TOOL_ALIASES[tool] for tool in native))
    body = text.split("---", 2)[2].lstrip("\n")
    return (
        f"---\nname: {json.dumps(fields['name'])}\n"
        f"description: {json.dumps(fields['description'])}\n"
        f"tools: [{', '.join(aliases)}]\n---\n\n"
        f"<!-- Generated by tools/setup_agent_platforms.py from .claude/agents/{path.name}; "
        f"SHA-256 {sha256_file(path)}. Edit the canonical profile, not this adapter. -->\n\n{body}"
    )


def same_target(alias: Path, target: Path) -> bool:
    try:
        return alias.resolve(strict=True) == target.resolve(strict=True)
    except (OSError, RuntimeError):
        return False


def make_alias(alias: Path, target: Path) -> None:
    if same_target(alias, target):
        return
    if alias.exists() or alias.is_symlink():
        # An empty directory can be replaced; existing content must be preserved.
        if not alias.is_dir() or alias.is_symlink():
            raise ValueError(f"Refusing to replace existing alias/file: {alias}")
        children = list(alias.rglob("*"))
        if any(not child.is_dir() or child.is_symlink() for child in children):
            raise ValueError(f"Refusing to overwrite nonempty skill directory: {alias}")
        for child in sorted(children, key=lambda p: len(p.parts), reverse=True):
            child.rmdir()
        alias.rmdir()
    alias.parent.mkdir(parents=True, exist_ok=True)
    try:
        os.symlink(os.path.relpath(target, alias.parent), alias, target_is_directory=True)
    except OSError:
        if os.name != "nt":
            raise
        # Junctions do not require Developer Mode/admin, unlike some symlink setups.
        subprocess.run(["cmd", "/c", "mklink", "/J", str(alias), str(target)],
                       capture_output=True, check=True)


def configure(root: Path, check: bool = False) -> tuple[int, int]:
    root = root.resolve()
    skills = sorted(p.parent for p in (root / SKILLS).glob("*/SKILL.md"))
    agents = sorted((root / AGENTS).glob("*.agent.md"))
    if not skills or not agents:
        raise ValueError("Canonical skills or Claude agent profiles are missing.")
    failures = []
    for skill in skills:
        fields = metadata((skill / "SKILL.md").read_text(encoding="utf-8-sig"))
        if fields.get("name") != skill.name or not fields.get("description"):
            raise ValueError(f"Invalid skill metadata: {skill}")
        for directory in (".claude/skills", ".github/skills"):
            alias = root / directory / skill.name
            if check:
                if not same_target(alias, skill):
                    failures.append(f"missing/stale skill alias: {alias}")
            else:
                make_alias(alias, skill)
    expected_paths = {root / COPILOT / agent.name for agent in agents}
    for path in (root / COPILOT).glob("*.agent.md"):
        if path not in expected_paths:
            failures.append(f"Unexpected Copilot profile; remove or migrate deliberately: {path}")
    names = set()
    for agent in agents:
        name = metadata(agent.read_text(encoding="utf-8-sig"))["name"]
        if name in names:
            raise ValueError(f"Duplicate agent name: {name}")
        names.add(name)
        destination = root / COPILOT / agent.name
        rendered = render_copilot_agent(agent)
        if check:
            if not destination.is_file() or destination.read_text(encoding="utf-8-sig") != rendered:
                failures.append(f"missing/stale Copilot adapter: {destination}")
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(rendered, encoding="utf-8")
    if failures:
        raise ValueError("\n".join(failures))
    return len(skills), len(agents)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        skills, agents = configure(args.repo_root, args.check)
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        parser.error(str(error))
    print(f"{'Verified' if args.check else 'Configured'} {skills} canonical skill(s), "
          f"Claude/Copilot discovery aliases and {agents} Copilot agent adapters.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())